from django.db import models as models

class Weather(models.Model):
    swell_period = models.CharField(max_length=200,null=True)
    wind_dir = models.CharField(max_length=200,null=True)
    lat = models.CharField(max_length=200,null=True)
    cloud_oktas = models.CharField(max_length=200,null=True)
    gust_kt = models.CharField(max_length=200,null=True)
    history_product = models.CharField(max_length=200,null=True)
    local_date_time_full = models.CharField(max_length=200,null=True)
    cloud = models.CharField(max_length=200,null=True)
    press_msl = models.CharField(max_length=200,null=True)
    cloud_type = models.CharField(max_length=200,null=True)
    wind_spd_kmh = models.CharField(max_length=200,null=True)
    lon = models.CharField(max_length=200,null=True)
    swell_height = models.CharField(max_length=200,null=True)
    wmo = models.CharField(max_length=200,null=True)
    press_qnh = models.CharField(max_length=200,null=True)
    weather = models.CharField(max_length=200,null=True)
    wind_spd_kt = models.CharField(max_length=200,null=True)
    rain_trace = models.CharField(max_length=200,null=True)
    aifstime_utc = models.CharField(max_length=200,null=True) 
    delta_t = models.CharField(max_length=200,null=True)
    press_tend = models.CharField(max_length=200,null=True)
    rel_hum = models.CharField(max_length=200,null=True)
    local_date_time = models.CharField(max_length=200,null=True)
    press = models.CharField(max_length=200,null=True)
    vis_km = models.CharField(max_length=200,null=True)
    sea_state = models.CharField(max_length=200,null=True)
    air_temp = models.CharField(max_length=200,null=True)
    name = models.CharField(max_length=200,null=True)
    cloud_base_m = models.CharField(max_length=200,null=True)
    cloud_type_id = models.CharField(max_length=200,null=True)
    gust_kmh = models.CharField(max_length=200,null=True)
    dewpt = models.CharField(max_length=200,null=True)
    swell_dir_worded = models.CharField(max_length=200,null=True)
    sort_order = models.CharField(max_length=200,null=True)
    apparent_t = models.CharField(max_length=200,null=True)
    def __str__(self):
        return self.weather_text
